# Generated by Django 5.2.8 on 2025-01-18 00:00

import re
import django.contrib.auth.validators
from django.db import migrations, models
import core.models


def populate_usernames(apps, schema_editor):
    User = apps.get_model('core', 'User')

    existing = set(
        User.objects.exclude(username__isnull=True).exclude(username='').values_list('username', flat=True)
    )
    existing_lower = {name.lower() for name in existing}

    def normalized_base(value, fallback):
        candidate = (value or '').strip()
        candidate = candidate.split('@')[0] if '@' in candidate else candidate
        candidate = re.sub(r'[^\w.@+-]', '', candidate.lower())[:150]
        return candidate or fallback

    for user in User.objects.all().order_by('id'):
        if user.username:
            continue

        base = normalized_base(user.email, f"user{user.id}")
        candidate = base
        suffix = 1

        while candidate.lower() in existing_lower:
            candidate = f"{base}{suffix}"
            if len(candidate) > 150:
                trimmed = base[: max(1, 150 - len(str(suffix)))]
                candidate = f"{trimmed}{suffix}"
            suffix += 1

        user.username = candidate
        user.save(update_fields=['username'])
        existing.add(candidate)
        existing_lower.add(candidate.lower())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                error_messages={
                    'unique': 'A user with that username already exists.',
                },
            ),
        ),
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                error_messages={
                    'unique': 'A user with that username already exists.',
                },
            ),
        ),
    ]
