# Generated by Django 5.2.8 on 2025-11-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('cooking', 'Cooking'), ('outdoor', 'Outdoor'), ('shopping', 'Shopping'), ('pet_care', 'Pet Care'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('base_points', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assignment_type', models.CharField(choices=[('assigned', 'Assigned'), ('global', 'Global (Anyone)'), ('rotating', 'Rotating')], default='assigned', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('recurrence_pattern', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='none', max_length=10)),
                ('recurrence_data', models.JSONField(blank=True, help_text='Additional recurrence configuration', null=True)),
                ('requires_verification', models.BooleanField(default=False)),
                ('verification_photo_required', models.BooleanField(default=False)),
                ('estimated_minutes', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('expired', 'Expired')], default='available', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completion_photo', models.ImageField(blank=True, null=True, upload_to='chore_completions/')),
                ('completion_notes', models.TextField(blank=True)),
                ('points_awarded', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chore_instances',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('cooking', 'Cooking'), ('outdoor', 'Outdoor'), ('shopping', 'Shopping'), ('pet_care', 'Pet Care'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('suggested_points', models.IntegerField(default=10)),
                ('estimated_minutes', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chore_templates',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChoreTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chore_transfers',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('chore_assigned', 'Chore Assigned'), ('chore_due', 'Chore Due Soon'), ('chore_overdue', 'Chore Overdue'), ('transfer_request', 'Transfer Request'), ('transfer_accepted', 'Transfer Accepted'), ('transfer_rejected', 'Transfer Rejected'), ('reward_approved', 'Reward Approved'), ('reward_rejected', 'Reward Rejected'), ('points_awarded', 'Points Awarded'), ('streak_milestone', 'Streak Milestone'), ('leaderboard_rank', 'Leaderboard Update')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
