# Generated by Django 5.2.8 on 2025-11-23 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chores', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chore',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chore',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='households.household'),
        ),
        migrations.AddField(
            model_name='choreinstance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chore_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choreinstance',
            name='chore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.chore'),
        ),
        migrations.AddField(
            model_name='choreinstance',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='User who claimed a global chore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_chore_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choreinstance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_chore_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choretemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choretemplate',
            name='household',
            field=models.ForeignKey(blank=True, help_text='Null means system-wide template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chore_templates', to='households.household'),
        ),
        migrations.AddField(
            model_name='choretransfer',
            name='chore_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='chores.choreinstance'),
        ),
        migrations.AddField(
            model_name='choretransfer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choretransfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='households.household'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
