# Generated by Django 5.2.8 on 2025-11-23 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_initial'),
        ('households', '0002_leaderboard_leaderboard_househo_e8ed20_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='base_points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='chore',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choreinstance',
            name='points_awarded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choretemplate',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choretemplate',
            name='suggested_points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddIndex(
            model_name='chore',
            index=models.Index(fields=['household', 'status', 'priority'], name='chores_househo_8e293c_idx'),
        ),
        migrations.AddIndex(
            model_name='chore',
            index=models.Index(fields=['household', 'assignment_type'], name='chores_househo_df4c35_idx'),
        ),
        migrations.AddIndex(
            model_name='choreinstance',
            index=models.Index(fields=['status', 'due_date'], name='chore_insta_status_28ab71_idx'),
        ),
        migrations.AddIndex(
            model_name='choreinstance',
            index=models.Index(fields=['status', 'assigned_to'], name='chore_insta_status_224b77_idx'),
        ),
    ]
