# Generated by Django 5.2.8 on 2025-11-23 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_alter_chore_base_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='current_rotation_index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChoreRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='chores.chore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chore_rotations',
                'ordering': ['position', 'id'],
                'unique_together': {('chore', 'user')},
            },
        ),
    ]
