# Generated by Django 5.2.8 on 2025-11-25 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_chore_current_rotation_index_chorerotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='choreinstance',
            index=models.Index(fields=['chore', 'status', 'due_date'], name='cinst_house_status_due_idx'),
        ),
    ]
