# Generated by Django 5.2.8 on 2025-11-23 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('point_cost', models.IntegerField()),
                ('category', models.CharField(choices=[('privilege', 'Privilege'), ('item', 'Item'), ('activity', 'Activity'), ('other', 'Other')], max_length=20)),
                ('quantity_available', models.IntegerField(blank=True, help_text='Leave blank for unlimited quantity', null=True)),
                ('quantity_remaining', models.IntegerField(blank=True, help_text='Auto-calculated based on quantity_available', null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='reward_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, help_text='Reward becomes available from this date', null=True)),
                ('available_until', models.DateTimeField(blank=True, help_text='Reward available until this date', null=True)),
                ('max_redemptions_per_user', models.IntegerField(blank=True, help_text='Max times a single user can redeem this reward', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rewards', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='households.household')),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['point_cost', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('redemption_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_redemptions', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='households.household')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_redemptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
