# Generated by Django 5.2.8 on 2025-11-23 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_leaderboard_leaderboard_househo_e8ed20_idx_and_more'),
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='point_cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='quantity_available',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited quantity', null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='quantity_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated based on quantity_available', null=True),
        ),
        migrations.AlterField(
            model_name='rewardredemption',
            name='points_spent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__isnull', True), ('quantity_remaining__isnull', True), ('quantity_remaining__lte', models.F('quantity_available')), _connector='OR'), name='reward_quantity_remaining_lte_available'),
        ),
    ]
