# Generated by hand to align with updated Reward/RewardRedemption models.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_leaderboard_leaderboard_househo_e8ed20_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0002_alter_reward_point_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='max_redemptions_per_user',
            new_name='per_user_limit',
        ),
        migrations.AlterField(
            model_name='reward',
            name='per_user_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max times a single user can redeem this reward', null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='cooldown_days',
            field=models.PositiveIntegerField(blank=True, help_text='Cooldown (in days) before the same user can redeem again', null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reward_images/'),
        ),
        migrations.AddField(
            model_name='reward',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reward',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Show low-stock alert at or below this remaining quantity', null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='If false, redemption auto-approves when constraints pass'),
        ),
        migrations.AddField(
            model_name='reward',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for filtering', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(check=models.Q(('point_cost__gt', 0)), name='reward_point_cost_gt_zero'),
        ),
        migrations.RenameField(
            model_name='rewardredemption',
            old_name='redemption_notes',
            new_name='user_note',
        ),
        migrations.RemoveField(
            model_name='rewardredemption',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='rewardredemption',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='reward_proofs/'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['reward', 'status'], name='rewardred_reward__37cfd8_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['user', 'status'], name='rewardred_user_id_e72cae_idx'),
        ),
    ]
