# Generated by hand to add allowed_members restriction support.
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0003_rewards_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='allowed_members',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to allow anyone in the household to claim', related_name='restricted_rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
