# Generated by Django 5.2.8 on 2025-11-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_reward_allowed_members'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rewardredemption',
            new_name='reward_rede_reward__89996b_idx',
            old_name='rewardred_reward__37cfd8_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardredemption',
            new_name='reward_rede_user_id_cee4b8_idx',
            old_name='rewardred_user_id_e72cae_idx',
        ),
        migrations.AlterField(
            model_name='rewardredemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
