"""
Django settings for choremanager project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-%skld3nb1pelg2ac7l_wzfi(wsi%)5w$co(&-z-v7)z1pqdkbl')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'drf_spectacular',

    # Local apps
    'core.apps.CoreConfig',
    'households.apps.HouseholdsConfig',
    'chores.apps.ChoresConfig',
    'rewards.apps.RewardsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'choremanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.contact_email',
            ],
        },
    },
]

WSGI_APPLICATION = 'choremanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if MySQL environment variables are set
MYSQL_HOST = config('MYSQL_HOST', default='')

if MYSQL_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('MYSQL_DATABASE', default='choremanager'),
            'USER': config('MYSQL_USER', default='choreuser'),
            'PASSWORD': config('MYSQL_PASSWORD', default='chorepass123'),
            'HOST': MYSQL_HOST,
            'PORT': config('MYSQL_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []  # Disable password strength/length requirements


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.User'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
CONTACT_EMAIL = config('CONTACT_EMAIL', default='')

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_LIFETIME_MINUTES', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_LIFETIME_DAYS', default=7, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# API Documentation Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Chore Manager API',
    'DESCRIPTION': 'API for household chore management and gamification',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:8000',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
if EMAIL_BACKEND != 'django.core.mail.backends.console.EmailBackend':
    EMAIL_HOST = config('EMAIL_HOST', default='')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Application-specific settings
CHORE_VERIFICATION_REQUIRED_BY_DEFAULT = config('CHORE_VERIFICATION_REQUIRED_BY_DEFAULT', default=True, cast=bool)
POINTS_MULTIPLIER_EASY = config('POINTS_MULTIPLIER_EASY', default=1, cast=int)
POINTS_MULTIPLIER_MEDIUM = config('POINTS_MULTIPLIER_MEDIUM', default=2, cast=int)
POINTS_MULTIPLIER_HARD = config('POINTS_MULTIPLIER_HARD', default=3, cast=int)
POINTS_MULTIPLIER_EXPERT = config('POINTS_MULTIPLIER_EXPERT', default=5, cast=int)

# Demo and default values
DEMO_USER_PASSWORD = config('DEMO_USER_PASSWORD', default='demo1234')
DEFAULT_REMINDER_TIME = config('DEFAULT_REMINDER_TIME', default='18:00')

# Upload validation settings
MAX_UPLOAD_SIZE_MB = config('MAX_UPLOAD_SIZE_MB', default=5, cast=int)
MAX_IMAGE_DIMENSION = config('MAX_IMAGE_DIMENSION', default=4096, cast=int)

# Celery / background tasks
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

REMINDER_LEAD_TIME_MINUTES = config('REMINDER_LEAD_TIME_MINUTES', default=60, cast=int)
REMINDER_COOLDOWN_MINUTES = config('REMINDER_COOLDOWN_MINUTES', default=120, cast=int)
REMINDER_SCAN_INTERVAL_MINUTES = config('REMINDER_SCAN_INTERVAL_MINUTES', default=1440, cast=int)
REMINDER_SCHEDULE_DIGEST_INTERVAL_MINUTES = config('REMINDER_SCHEDULE_DIGEST_INTERVAL_MINUTES', default=5, cast=int)
RECURRENCE_GENERATE_INTERVAL_MINUTES = config('RECURRENCE_GENERATE_INTERVAL_MINUTES', default=60, cast=int)
RECURRENCE_LOOKAHEAD_DAYS = config('RECURRENCE_LOOKAHEAD_DAYS', default=30, cast=int)
STREAK_ROLLUP_INTERVAL_MINUTES = config('STREAK_ROLLUP_INTERVAL_MINUTES', default=1440, cast=int)
NOTIFICATION_RETENTION_DAYS = config('NOTIFICATION_RETENTION_DAYS', default=90, cast=int)
COMPLETED_INSTANCE_RETENTION_DAYS = config('COMPLETED_INSTANCE_RETENTION_DAYS', default=180, cast=int)

CELERY_BEAT_SCHEDULE = {
    "scan_due_chore_items": {
        "task": "chores.tasks.scan_due_items",
        "schedule": timedelta(minutes=REMINDER_SCAN_INTERVAL_MINUTES),
    },
    "send_scheduled_chore_digests": {
        "task": "chores.tasks.send_scheduled_chore_digests",
        "schedule": timedelta(minutes=REMINDER_SCHEDULE_DIGEST_INTERVAL_MINUTES),
    },
    "generate_recurring_chore_instances": {
        "task": "chores.tasks.generate_recurring_instances",
        "schedule": timedelta(minutes=RECURRENCE_GENERATE_INTERVAL_MINUTES),
    },
    "recompute_streaks_and_leaderboards": {
        "task": "chores.tasks.recompute_streaks_and_leaderboards",
        "schedule": timedelta(minutes=STREAK_ROLLUP_INTERVAL_MINUTES),
    },
}

# Home Assistant notifications (global fallback; per-household settings are preferred)
HA_BASE_URL = config('HA_BASE_URL', default='')
HA_LONG_LIVED_TOKEN = config('HA_LONG_LIVED_TOKEN', default='')
HA_DEFAULT_NOTIFY_TARGET = config('HA_DEFAULT_NOTIFY_TARGET', default='')
HA_VERIFY_SSL = config('HA_VERIFY_SSL', default=True, cast=bool)
