# Generated by Django 5.2.8 on 2025-11-23 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['household', 'period'], name='leaderboard_househo_e8ed20_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['household', 'period', 'rank'], name='leaderboard_househo_6d26e6_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', 'created_at'], name='point_trans_user_id_7622fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['household', 'created_at'], name='point_trans_househo_1e23fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='streakbonus',
            constraint=models.CheckConstraint(condition=models.Q(('streak_days__gte', 1)), name='streak_bonus_streak_days_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='streakbonus',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_points__gte', 0)), name='streak_bonus_points_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='streakbonus',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_percentage__isnull', True), ('bonus_percentage__gte', 0), _connector='OR'), name='streak_bonus_percentage_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('current_points__gte', 0)), name='user_score_current_points_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('lifetime_points__gte', 0)), name='user_score_lifetime_points_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('current_streak__gte', 0)), name='user_score_current_streak_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('longest_streak__gte', 0)), name='user_score_longest_streak_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('total_chores_completed__gte', 0)), name='user_score_total_completed_gte_0'),
        ),
    ]
