# Generated by Django 5.2.8 on 2025-11-25 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_household_homeassistant_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leaderboard',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 0), ('chores_completed__gte', 0), ('rank__gte', 0)), name='leaderboard_non_negative_fields'),
        ),
        migrations.AddConstraint(
            model_name='pointtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='point_transaction_balance_after_gte_0'),
        ),
    ]
