# Generated by Django 5.2.8 on 2025-11-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0005_leaderboard_leaderboard_non_negative_fields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='timezone',
            field=models.CharField(default=settings.TIME_ZONE, help_text='IANA timezone used to schedule reminders (e.g., America/New_York).', max_length=50),
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day_time', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('default_channel_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminder_schedules', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminder_schedules',
                'ordering': ['-updated_at'],
                'unique_together': {('household', 'user')},
            },
        ),
    ]
