# Generated by Django 5.2.8 on 2025-11-25 13:13

from django.conf import settings
from django.db import migrations


DEFAULT_SEND_TIME = "18:00"
DAY_KEYS = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]


def backfill_timezones_and_schedules(apps, schema_editor):
    Household = apps.get_model("households", "Household")
    HouseholdMembership = apps.get_model("households", "HouseholdMembership")
    ReminderSchedule = apps.get_model("households", "ReminderSchedule")

    default_tz = getattr(settings, "TIME_ZONE", "UTC")
    per_day_time = {day: DEFAULT_SEND_TIME for day in DAY_KEYS}

    for household in Household.objects.all().iterator():
        if not household.timezone:
            household.timezone = default_tz
            household.save(update_fields=["timezone"])

        memberships = HouseholdMembership.objects.filter(household=household).select_related("user")
        for membership in memberships:
            ReminderSchedule.objects.get_or_create(
                household=household,
                user=membership.user,
                defaults={
                    "per_day_time": per_day_time,
                    "active": True,
                    "created_by": household.created_by,
                },
            )


def noop_reverse(apps, schema_editor):
    # Leave schedules and timezones intact on reverse; no destructive rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0006_household_timezone_reminderschedule"),
    ]

    operations = [
        migrations.RunPython(backfill_timezones_and_schedules, noop_reverse),
    ]
